.PHONY: clean All

All:
	@echo "----------Building project:[ pec1_chess - Debug ]----------"
	@cd "pec1_chess" && "$(MAKE)" -f  "pec1_chess.mk"
clean:
	@echo "----------Cleaning project:[ pec1_chess - Debug ]----------"
	@cd "pec1_chess" && "$(MAKE)" -f  "pec1_chess.mk" clean
